export enum LotStatus {
  PENDING = 'PENDING',
  IN_KNITTING = 'IN_KNITTING',
  IN_DYEING = 'IN_DYEING',
  IN_COMPACTING = 'IN_COMPACTING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
